coffeebreak/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('raffle/', include('raffle.urls')),
]

raffle/urls.py
from django.conf.urls import include
from django.urls import path

from . import views
app_name = 'raffle'
urlpatterns = [
    path('', views.index, name='index'),
    path('createRaffle/', views.createRaffle, name='createRaffle'),
    path('listRaffle/<int:id>', views.ListRaffleView.as_view(), name='listRaffle'),
    path('change', views.change, name='change'),
]

raffle/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    name_text = models.CharField(max_length=40)
    active = models.BooleanField(default=True)
    def __str__(self):
        return self.name_text

class Event(models.Model):
    event_name_text = models.CharField(max_length=20)

    def __str__(self):
        return self.event_name_text

class Pairing(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    personA = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='personA')
    personB = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='personB')

    cleaning_task = models.BooleanField(default = False)

    def __str__(self):
        return self.event.__str__() + " => " + self.personA.__str__() + " - " + self.personB.__str__()

raffle/forms.py
from django import forms
from .models import *

class CreatRaffleForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ['event_name_text']

    persons = forms.ModelMultipleChoiceField(
        queryset=Person.objects.all().filter(active=True),
        initial=Person.objects.all().filter(active=True),
        widget=forms.CheckboxSelectMultiple
    )

raffle/views.py
from ast import Try
from django.shortcuts import render
from django.http import HttpResponseRedirect
# Create your views here.
from .forms import CreatRaffleForm
from django.views import generic
from datetime import datetime
from django.db.models import Q
from django.db.models import Count

import random
from .models import *

def index(request):
    return HttpResponseRedirect('/raffle/createRaffle/')

def change(request):

    raffleID = int(request.GET.get('raffleID'))
    compareID = int(request.GET.get('compare'))
    comparePerson = Person.objects.get(pk=compareID)
    changewithID = int(request.GET.get('changewith'))
    changewithPerson = Person.objects.get(pk=changewithID)

    pairingA = Pairing.objects.filter(Q(personA=compareID) | Q(personB=compareID)).filter(event=raffleID)[0]
    pairingB = Pairing.objects.filter(Q(personA=changewithID) | Q(personB=changewithID)).filter(event=raffleID)[0]

    if pairingA.personA == compareID:
        pairingA.personA = changewithPerson
    else:
        pairingA.personB = changewithPerson

    if pairingB.personA == changewithID:
        pairingB.personA = comparePerson
    else:
        pairingB.personB = comparePerson

    pairingA.save()
    pairingB.save()

    return HttpResponseRedirect('/raffle/listRaffle/' + str(raffleID))

def createRaffle(request):

    if request.method == 'POST':
        form = CreatRaffleForm(request.POST)
        if form.is_valid():
            random.seed(datetime.now())
            new_event = form.save()
            persons_set = form.cleaned_data.get('persons')
            persons_list = list(persons_set)
            random.shuffle(persons_list)
            print(persons_list)
            count = persons_set.count() - 1
            loops = count / 2
            while count >= 0:
                newPair = Pairing(id=None, event=new_event, personA=persons_list[count], personB=persons_list[count - 1])
                newPair.save()
                count = count - 2
            
            return HttpResponseRedirect('/raffle/listRaffle/' + str(new_event.id))

    else:
        form = CreatRaffleForm()
    return render(request, 'raffle/createRaffle.html', {'form': form})

class ListRaffleView(generic.ListView):
    template_name = 'raffle/listEntry.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        pkID = self.kwargs['id'] 
        context['pkID'] = pkID

        showSum = self.request.GET.get('showSum')
        if showSum == '1':
            context['showSum'] = '1'

        comparePerson = None
        try:
            compareID = int(self.request.GET.get('compare'))
            if compareID >= 0:
                comparePerson = Person.objects.get(pk=compareID)
        except:
            None

        if comparePerson != None:
            context['comparePerson'] = comparePerson
            object_list = context['object_list']
            for entry in object_list:
                entry.personA.repeate = Pairing.objects.all().filter(personA=entry.personA, personB=compareID).count()
                entry.personA.repeate += Pairing.objects.all().filter(personA=compareID, personB=entry.personA).count()
                entry.personB.repeate = Pairing.objects.all().filter(personA=entry.personB, personB=compareID).count()
                entry.personB.repeate += Pairing.objects.all().filter(personA=compareID, personB=entry.personB).count()
           
            context['object_list'] = object_list

        return context
        

    def get_queryset(self): # new
        object_list = []
        pk_url_kwarg = "post_id"
        query = self.kwargs['id']  

#        all_queryset = QuerySet.create(list(chain(Site.objects.all(), Medium.objects.all())))
        object_list.extend(list(Pairing.objects.filter(
                Q(event=query)
        )))

        for entry in object_list:

            entry.personA.cleanings = Pairing.objects.all().filter(cleaning_task=True).filter(Q(personA=entry.personA)|Q(personB=entry.personA)).count()
            entry.personB.cleanings = Pairing.objects.all().filter(cleaning_task=True).filter(Q(personA=entry.personB)|Q(personB=entry.personB)).count()

            entry.repeate = Pairing.objects.all().filter(personA=entry.personA, personB=entry.personB).count()
            entry.repeate += Pairing.objects.all().filter(personA=entry.personB, personB=entry.personA).count()
            entry.repeate -= 1

        return object_list

raffle/templates/raffle/createRaffle.html
<form action="{% url 'raffle:createRaffle' %}" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>

raffle/templates/raffle/listEntry.html
<html>
<body>
<h1>Paarungen</h1>

<style type="text/css">
    customers tr:nth-child(even){background-color: #f2f200;};
    customers tr:hover {background-color: #ddd;};
  </style>
  <a href="{{ build_absolute_uri }}">reset</a>
  {{ comparePerson }}

  <form method='post' action='/add-edit-user/'>
    {% csrf_token %}
  </form>
<table border="2">
    <tr>
        <th>Person A</th>
        <th>Person B</th>
        <th>Bisherige Vorkommen</th>
        <th>Wiederholung mit A</th>
        <th>Wiederholung mit B</th>
        <th>Betreuung</th>
    </tr>
    {% for entry in object_list %}
    <tr>
        <td>{% if comparePerson %}<a href="{% url 'raffle:change' %}?raffleID={{ pkID }}&compare={{ comparePerson.id }}&changewith={{ entry.personA.id }}">{% endif %}
            {{ entry.personA }}{%if showSum == '1' %} ({{ entry.personA.cleanings }})
            {% endif %}{% if comparePerson %}</a>{% endif %}
        </td>
        <td>{% if comparePerson %}<a href="{% url 'raffle:change' %}?raffleID={{ pkID }}&compare={{ comparePerson.id }}&changewith={{ entry.personB.id }}">{% endif %}
            {{ entry.personB }}{%if showSum == '1' %} ({{ entry.personB.cleanings }}){% endif %}
            {% if comparePerson %}</a>{% endif %}
        </td>
        <td>{{ entry.repeate }}</td>
        <td>{% if comparePerson == entry.personA %} --- {% else %}{{ entry.personA.repeate }}{% endif %}</td>
        <td>{{ entry.personB.repeate }}</td>
        <td>{{ entry.cleaning_task }}</td>
        <td><a href="{{ build_absolute_uri }}?compare={{ entry.personA.id }}">link</a></td>
        <td><a href="{{ build_absolute_uri }}?compare={{ entry.personB.id }}">link</a></td>
    </tr>
    {% endfor %}
</table>
</body>

</html>